#! /bin/sh

sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &

$HOME/.config/polybar/launch.sh &

xfce-power-manager &

bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.51

bspc config automatic_scheme     spiral

# from gitlab.com/protesilaos/dotfiles
bspc config single_monocle true # smart borders
bspc config borderless_monocle true # smart borders
bspc config gapless_monocle true # use "true" for smart gaps
bspc config paddingless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true # brings pointer to focused monitor (see workspaces)
bspc config pointer_modifier mod1 # ALT key (see why right below)
bspc config pointer_action1 move # alt + left-click to move node
bspc config pointer_action2 resize_side # alt + right-click to resize node splits
bspc config click_to_focus any # focus with any click
bspc config swallow_first_click false # play the mouse event (e.g. right click context menu)
bspc config initial_polarity first_child
bspc config ignore_ewmh_focus true # prevent focus stealing
# end ---

bspc rule -a emacs desktop='^1' follow=on state=tiled
bspc rule -a mailspring desktop='^2' follow=on state=tiled
bspc rule -a qutebrowser desktop='^3' follow=on state=tiled
bspc rule -a inkscape desktop='^4' follow=on state=tiled
bspc rule -a rstudio desktop='^4' follow=on state=tiled
bspc rule -a zathura follow=on state=floating
bspc rule -a mpv follow=on state=tiled
bspc rule -a telegram-desktop follow=on state=tiled
